/**
 * URD appendix seeds: professions, titles, specializations, regions, dial codes.
 * Admin can still add/edit via Settings; these are the baseline lists.
 */

export const URD_PROFESSIONS = [
  'Orthodontist',
  'Dentist',
  'Denturist / Clinical Denture Specialist',
  'General Practitioner',
  'Office Staff',
  'Treatment Coordinator',
  'Entrepreneur',
  'Company Owner – Dental Background',
  'Company Owner – Non-Dental Background',
] as const;

export const URD_PROFESSION_SPECIALIZATIONS = [
  'Owner of company',
  'Dental Technician',
  'Endodontist',
  'Esthetics',
  'General Dentist',
  'Orthodontist',
  'Paediatric Dentistry',
  'Periodontist',
  'Prosthodontist',
  'Other',
] as const;

export const URD_ACADEMIC_TITLES = [
  'Entrepreneur',
  'Dr.',
  'Prof.',
  'Prof. Dr.',
  'Other',
] as const;

export const URD_LANGUAGES = [
  'English',
  'Arabic',
  'French',
  'Spanish',
  'German',
  'Portuguese',
  'Chinese',
  'Italian',
  'Turkish',
] as const;

/** URD §18 region → country mapping (sales territories omitted). */
export const URD_REGION_COUNTRIES: Record<string, readonly string[]> = {
  NAM: ['Canada', 'New Caledonia', 'US Virgin Islands', 'United States'],
  APAC: [
    'Australia',
    'China',
    'Hong Kong',
    'India',
    'Japan',
    'Macau',
    'Malaysia',
    'New Zealand',
    'Philippines',
    'Singapore',
    'Taiwan',
    'Thailand',
    'Vietnam',
  ],
  CEMEA: [
    'Afghanistan',
    'Algeria',
    'Angola',
    'Armenia',
    'Austria',
    'Bosnia and Herzegovina',
    'Botswana',
    'Bulgaria',
    'Croatia',
    'Czech Republic',
    'Germany',
    'Ghana',
    'Greece',
    'Hungary',
    'Iceland',
    'Iraq',
    'Israel',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kuwait',
    'Lebanon',
    'Liechtenstein',
    'Lithuania',
    'Malta',
    'Mauritius',
    'Morocco',
    'Mozambique',
    'Namibia',
    'Oman',
    'Poland',
    'Romania',
    'Saudi Arabia',
    'Slovakia',
    'Slovenia',
    'South Africa',
    'Switzerland',
    'Turkey',
    'Ukraine',
    'United Arab Emirates',
    'Zimbabwe',
  ],
  LATAM: [
    'Argentina',
    'Brazil',
    'Chile',
    'Colombia',
    'Costa Rica',
    'Mexico',
    'Peru',
    'Uruguay',
  ],
  WEU: [
    'Andorra',
    'Belgium',
    'Denmark',
    'Finland',
    'France',
    'French Guiana',
    'French Polynesia',
    'Guadeloupe',
    'Holy See (Vatican City)',
    'Ireland',
    'Italy',
    'Jersey',
    'Luxembourg',
    'Martinique',
    'Monaco',
    'Netherlands',
    'Norway',
    'Portugal',
    'Reunion',
    'Saint Pierre and Miquelon',
    'San Marino',
    'Spain',
    'Sweden',
    'United Kingdom',
    'Wallis and Futuna',
  ],
};

/** International dialing codes from URD Country Codes Data. */
export const URD_DIAL_CODES: Record<string, string> = {
  Albania: '+355',
  Algeria: '+213',
  Andorra: '+376',
  Angola: '+244',
  Argentina: '+54',
  Australia: '+61',
  Austria: '+43',
  Belgium: '+32',
  'Bosnia and Herzegovina': '+387',
  Brazil: '+55',
  Bulgaria: '+359',
  Canada: '+1',
  Chile: '+56',
  China: '+86',
  Colombia: '+57',
  'Costa Rica': '+506',
  Croatia: '+385',
  Cyprus: '+357',
  'Czech Republic': '+420',
  Denmark: '+45',
  'Dominican Republic': '+1',
  Egypt: '+20',
  'El Salvador': '+503',
  Estonia: '+372',
  'Faroe Islands': '+298',
  Finland: '+358',
  France: '+33',
  'French Guiana': '+594',
  'French Guyana': '+594',
  Georgia: '+995',
  Germany: '+49',
  Gibraltar: '+350',
  Greece: '+30',
  Greenland: '+299',
  Guadeloupe: '+590',
  Guatemala: '+502',
  Honduras: '+504',
  'Hong Kong': '+852',
  Hungary: '+36',
  Iceland: '+354',
  India: '+91',
  Indonesia: '+62',
  Iraq: '+964',
  Ireland: '+353',
  Israel: '+972',
  Italy: '+39',
  'Ivory Coast': '+225',
  Japan: '+81',
  Jordan: '+962',
  Kuwait: '+965',
  Latvia: '+371',
  Lebanon: '+961',
  Liechtenstein: '+423',
  Lithuania: '+370',
  Luxembourg: '+352',
  Malaysia: '+60',
  Malta: '+356',
  Martinique: '+596',
  Mexico: '+52',
  Moldova: '+373',
  Montenegro: '+382',
  Morocco: '+212',
  Namibia: '+264',
  Nepal: '+977',
  Netherlands: '+31',
  'New Caledonia': '+687',
  'New Zealand': '+64',
  Nicaragua: '+505',
  Nigeria: '+234',
  Norway: '+47',
  Oman: '+968',
  Pakistan: '+92',
  Panama: '+507',
  Peru: '+51',
  Philippines: '+63',
  Poland: '+48',
  Portugal: '+351',
  'Puerto Rico': '+1',
  Qatar: '+974',
  Reunion: '+262',
  Romania: '+40',
  'Saudi Arabia': '+966',
  Serbia: '+381',
  Singapore: '+65',
  Slovakia: '+421',
  Slovenia: '+386',
  'South Africa': '+27',
  'South Korea': '+82',
  Spain: '+34',
  Suriname: '+597',
  Sweden: '+46',
  Switzerland: '+41',
  Taiwan: '+886',
  Thailand: '+66',
  Tunisia: '+216',
  Turkey: '+90',
  Ukraine: '+380',
  'United Arab Emirates': '+971',
  'United Kingdom': '+44',
  'United States': '+1',
  Uruguay: '+598',
  'US Virgin Islands': '+1',
  Venezuela: '+58',
  Vietnam: '+84',
  Zimbabwe: '+263',
};

export function regionCodeForCountry(name: string): string | null {
  for (const [code, countries] of Object.entries(URD_REGION_COUNTRIES)) {
    if (countries.includes(name)) return code;
  }
  return null;
}
